# Generated by Django 5.2 on 2025-04-07 06:09

import familylineage.core.utils
import thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=thumbnails.fields.ImageField(
                blank=True, null=True,
                upload_to=familylineage.core.utils.FilenameGenerator(prefix='persons')),
        ),
    ]
