# Generated by Django 5.2 on 2025-04-06 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_divorced', models.BooleanField(default=False)),
                ('husband', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='husband', to='persons.person')),
                ('wife', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='wife', to='persons.person')),
            ],
        ),
        migrations.CreateModel(
            name='ParentChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                            related_name='child', to='persons.person')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             related_name='parent', to='persons.person')),
            ],
        ),
    ]
