# Generated by Django 5.2 on 2025-04-07 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_person_photo'),
        ('relationships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentchild',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='parents_relations', to='persons.person'),
        ),
        migrations.AlterField(
            model_name='parentchild',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='children_relations', to='persons.person'),
        ),
    ]
